mspray/apps/reactive/irs/urls.py
"""urls module for Reactive IRS"""
from django.conf.urls import include
from django.urls import path

from rest_framework import routers

from mspray.apps.main.views import (
    districts,
    household,
    household_buffer,
    sprayday,
    target_area,
)
from mspray.apps.reactive.irs import performance
from mspray.apps.reactive.irs.views import (
    CHWListView,
    CHWLocationMapView,
    CHWTargetAreaListView,
    CHWTargetAreaMapView,
    CHWTargetAreaView,
    HomeView,
)

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path("", performance.DistrictPerfomanceView.as_view(), name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
    ],
    "mspray",
)

# pylint: disable=invalid-name
app_name = "reactive_irs"
urlpatterns = [
    path("", HomeView.as_view(), name="reactive_irs_home"),
    path("<int:pk>", CHWListView.as_view(), name="chw_list"),
    path("chw", CHWTargetAreaListView.as_view(), name="ta_list"),
    path("chw/<int:pk>", CHWTargetAreaView.as_view(), name="ta_list"),
    path("map/<int:pk>", CHWLocationMapView.as_view(), name="chw_list_map"),
    path("chw/map/<int:pk>", CHWLocationMapView.as_view(), name="chw_map"),
    path("api/", include(router.urls)),
    path(
        "chw/<int:district_pk>/<int:slug>",
        CHWTargetAreaMapView.as_view(),
        name="target_area_map",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
]

mspray/apps/reveal/urls.py
"""
reveal.urls module.
"""
from django.urls import path

from mspray.apps.reveal.views import add_spray_data_view

app_name = "reveal"  # pylint: disable=invalid-name

urlpatterns = [  # pylint: disable=invalid-name
    path("add-spray-data/", add_spray_data_view, name="add_spray_data")
]

mspray/urls.py
# -*- coding: utf-8 -*-
"""
Mspray urls module.
"""
import sys

from django.conf import settings
from django.conf.urls import include, static, url
from django.contrib import admin
from django.urls import path

from rest_framework import routers

from mspray.apps.alerts import urls as alerts_urls
from mspray.apps.main.views import directly_observed_spraying_form as dos_form
from mspray.apps.main.views import (
    districts, home, household, household_buffer, indicators, performance,
    spray_operator_daily, sprayday, target_area, user)
from mspray.apps.main.views.decision import DecisionView
from mspray.apps.main.views.mobilisation import MobilisationView
from mspray.apps.main.views.mopup import HealthFacilityMopUpView, MopUpView
from mspray.apps.main.views.sensitization_visit import SensitizationVisitView
from mspray.apps.main.views.sprayday import NoLocationSprayDayView
from mspray.apps.mda import urls as mda_urls
from mspray.apps.reactive.irs import urls as reactive_irs_urls
from mspray.apps.warehouse import urls as warehouse_urls

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

admin.autodiscover()

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path(
            "", performance.DistrictPerfomanceView.as_view(),
            name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
        path(
            "definitions-and-conditions",
            performance.DefinitionAndConditionView.as_view(),
            name="definitions-and-conditions",
        ),
    ],
    "mspray",
)

urlpatterns = [  # pylint: disable=invalid-name
    path("reactive/irs/", include(reactive_irs_urls,
                                  namespace="reactive_irs")),
    path("mda/", include(mda_urls, namespace="mda")),
    path("mda-round-2/", include(mda_urls, namespace="mda-2")),
    path("trials/", include("mspray.apps.trials.urls", namespace="trials")),
    path("api/alerts/", include(alerts_urls, namespace="alerts")),
    path("api/", include(router.urls)),
    path("", home.DistrictView.as_view(), name="index"),
    path("login", user.login, name="login"),
    path("logout", user.logout, name="logout"),
    path(
        "not-in-target-area/",
        NoLocationSprayDayView.as_view(),
        name="no_location_spray_effectiveness",
    ),
    path("warehouse/", include(warehouse_urls, namespace="warehouse")),
    path(r"<int:pk>", home.DistrictView.as_view(), name="district"),
    path(
        "<int:district_pk>/<int:slug>",
        home.TargetAreaView.as_view(),
        name="target_area",
    ),
    path("sprayareas", home.SprayAreaView.as_view(), name="sprayareas"),
    path(
        "detailed-sprayareas/",
        home.DetailedCSVView.as_view(),
        name="detailed_sprayareas",
    ),
    path(
        "weekly-report", home.WeeklyReportView.as_view(),
        name="weeklyreports"),
    path(
        "indicators/number_of_households",
        indicators.NumberOfHouseholdsIndicatorView.as_view(),
        name="number_of_housesholds",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
    path("reveal/", include("mspray.apps.reveal.urls", namespace="reveal")),
    path("admin/", admin.site.urls),
    path(
        "spray-operator-daily",
        spray_operator_daily.SprayOperatorDailyViewSet.as_view({
            "post": "create"
        }),
        name="spray-operator-daily",
    ),
    path(
        "directly-observed-spraying-form",
        dos_form.DirectlyObservedSprayingFormViewSet.as_view({
            "post": "create"
        }),
        name="directly-observed-spraying-form",
    ),
    path(
        "directly-observed-spraying",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="directly-observed-spraying",
    ),
    path(
        "directly-observed-spraying/<int:district>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-district",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-team-leader",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>/"
        "<int:spray_operator>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-spray-operator",
    ),
    path(
        "sensitization-visit",
        SensitizationVisitView.as_view(),
        name="sensitization-visit",
    ),
    path(
        "mobilisation-visit",
        MobilisationView.as_view(),
        name="mobilisation-visit"),
    path("decision-visit", DecisionView.as_view(), name="decision-visit"),
    path("mop-up", MopUpView.as_view(), name="mop-up"),
    path(
        "mop-up/<int:district>",
        HealthFacilityMopUpView.as_view(),
        name="mop-up"),
] + static.static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if (settings.DEBUG or TESTING) and "debug_toolbar" in settings.INSTALLED_APPS:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

mspray/apps/main/models/team_leader.py
# -*- coding: utf-8 -*-
"""
TeamLeader model.
"""
from django.contrib.gis.db import models


class TeamLeader(models.Model):
    """
    TeamLeader model.
    """

    code = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=255, db_index=1)
    location = models.ForeignKey(
        "Location", null=True, on_delete=models.CASCADE
    )
    data_quality_check = models.BooleanField(default=False)
    average_spray_quality_score = models.FloatField(default=0.0)

    class Meta:
        app_label = "main"

    def __str__(self):
        return "{}".format(self.name)

mspray/apps/reactive/irs/models.py
"""Reactive IRS model"""

from django.conf import settings
from django.contrib.gis.db import models
from django.utils.translation import ugettext as _

SRID = settings.MSPRAY_DEFAULT_SRID


class CommunityHealthWorker(models.Model):
    """Model definition for CommunityHealthWorker."""

    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    code = models.CharField(max_length=50, unique=True, db_index=True)
    name = models.CharField(max_length=255)
    geom = models.PointField(srid=SRID)
    bgeom = models.GeometryField(srid=SRID, null=True)
    location = models.ForeignKey(
        "main.Location",
        related_name="chw",
        null=True,
        on_delete=models.CASCADE)

    class Meta:
        """Meta definition for CommunityHealthWorker."""

        verbose_name = _("Community Health Worker")
        verbose_name_plural = _("Community Health Workers")

    def __str__(self):
        """Unicode representation of CommunityHealthWorker."""
        return self.name

mspray/apps/main/views/spray_operator_daily.py
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.exceptions import ParseError
from rest_framework import status

from mspray.apps.main.models import SprayOperatorDailySummary
from mspray.apps.main.serializers.sprayday import SprayOperatorDailySerializer
from mspray.apps.main.utils import add_spray_operator_daily


class SprayOperatorDailyViewSet(viewsets.ModelViewSet):
    queryset = SprayOperatorDailySummary.objects.all()
    serializer_class = SprayOperatorDailySerializer

    def create(self, request, *args, **kwargs):
        try:
            add_spray_operator_daily(request.data)
        except Exception as e:
            raise ParseError(e)

        return Response("Successfully created", status=status.HTTP_201_CREATED)

mspray/apps/mda/views/map.py
# -*- coding: utf-8 -*-
"""Map views"""
import json

from django.conf import settings
from django.views.generic import DetailView

from mspray.apps.main.mixins import SiteNameMixin
from mspray.apps.main.models import Location
from mspray.apps.main.query import get_location_qs
from mspray.apps.main.serializers.target_area import (
    GeoTargetAreaSerializer,
    TargetAreaQuerySerializer,
    TargetAreaSerializer,
    count_duplicates,
    get_duplicates,
)
from mspray.apps.main.utils import get_location_dict, parse_spray_date
from mspray.apps.main.views.target_area import (
    TargetAreaHouseholdsViewSet,
    TargetAreaViewSet,
)


class MapView(SiteNameMixin, DetailView):
    """Map View"""

    template_name = "map.html"
    model = Location
    slug_field = "pk"

    def get_queryset(self):

        return get_location_qs(super(MapView, self).get_queryset())

    def get_context_data(self, **kwargs):
        context = super(MapView, self).get_context_data(**kwargs)
        serializer_class = (
            TargetAreaQuerySerializer
            if settings.SITE_NAME == "namibia"
            else TargetAreaSerializer
        )
        location = context["object"]
        if location.level == "RHC":
            location = get_location_qs(
                Location.objects.filter(pk=location.pk), "RHC"
            ).first()
        serializer = serializer_class(
            location, context={"request": self.request}
        )
        context["target_data"] = serializer.data
        spray_date = parse_spray_date(self.request)
        if spray_date:
            context["spray_date"] = spray_date
        if settings.MSPRAY_SPATIAL_QUERIES or context["object"].geom:
            response = TargetAreaViewSet.as_view({"get": "retrieve"})(
                self.request, pk=context["object"].pk, format="geojson"
            )
            response.render()
            context["not_sprayable_value"] = getattr(
                settings, "NOT_SPRAYABLE_VALUE", "noteligible"
            )
            context["ta_geojson"] = response.content.decode()
            bgeom = settings.HH_BUFFER and settings.OSM_SUBMISSIONS

            if self.object.level in ["district", "RHC"]:
                data = GeoTargetAreaSerializer(
                    get_location_qs(
                        self.object.location_set.all(), self.object.level
                    ),
                    many=True,
                    context={"request": self.request},
                ).data
                context["hh_geojson"] = json.dumps(data)
            else:
                loc = context["object"]
                hhview = TargetAreaHouseholdsViewSet.as_view(
                    {"get": "retrieve"}
                )
                response = hhview(
                    self.request,
                    pk=loc.pk,
                    bgeom=bgeom,
                    spray_date=spray_date,
                    format="geojson",
                )
                response.render()
                context["hh_geojson"] = response.content.decode()
                sprayed_duplicates = list(
                    get_duplicates(loc, True, spray_date)
                )
                not_sprayed_duplicates = list(
                    get_duplicates(loc, False, spray_date)
                )
                context["sprayed_duplicates_data"] = json.dumps(
                    sprayed_duplicates
                )
                context["sprayed_duplicates"] = count_duplicates(
                    loc, True, spray_date
                )
                context["not_sprayed_duplicates_data"] = json.dumps(
                    not_sprayed_duplicates
                )
                context["not_sprayed_duplicates"] = count_duplicates(
                    loc, False
                )

        context["districts"] = (
            Location.objects.filter(parent=None)
            .values_list("id", "code", "name")
            .order_by("name")
        )

        context.update({"map_menu": True})
        context.update(get_location_dict(self.object.pk))
        context["not_sprayed_reasons"] = json.dumps(
            settings.MSPRAY_UNSPRAYED_REASON_OTHER
        )

        return context

mspray/apps/reactive/irs/templates/reactive_irs/list.html
{% extends 'home/base.html' %}

{% load humanize %}
{% load staticfiles %}
{% load performance_extras %}
{% load progress_extras %}
{% load i18n %}

{% block content %}
<div class="container" id="district_table">
    <div "col-sm-12" id="table-container">
        <h1 id="district-name">
            {% if location %}
                {% if is_home_page %}
                Reactive IRS: {{location.name}}
                {% else %}
                Community Health Workers: {{location.name}}
                {% endif %}
                <a href="{% url 'reactive_irs:chw_list_map' location.id %}">
                    <i class="fa fa-map"></i>
                </a>
            {% else %}
                Reactive IRS
            {% endif %}
        </h1>
        <table id="target_areas" class="table table-stripe">
            <thead>
                <tr>
                    <th>Health Facilities</th>
                    <th>Structures on ground</th>
                    <th>Found</th>
                    <th>Sprayed</th>
                    <th>Spray Coverage</th>
                    <th>Found coverage</th>
                    <th>Spray Success Rate</th>
                </tr>
            </thead>
            <tbody>
                {% for chw in item_list %}
                    <tr>
                        <td>
                            {% if chw.structures > 0 %}
                                {% if location %}
                                    <a href="{% url 'reactive_irs:chw_map' chw.id %}">
                                    <i class="fa fa-map"></i>
                                    </a>
                                    <a href="{% url 'reactive_irs:ta_list' chw.id %}">
                                {% else %}
                                    <a href="{% url 'reactive_irs:chw_list' chw.id %}">
                                {% endif %}
                            {% endif %}
                                {{ chw.name }}
                            </a>
                        </td>
                        <td class='numbers'>{{ chw.structures|intcomma }}</td>
                        <td class='numbers'>{{ chw.found|intcomma }}</td>
                        <td class='numbers'>{{ chw.visited_sprayed|intcomma }}</td>
                        {% calc_percentage chw.visited_sprayed chw.structures as spray_effectiveness_percentage %}
                        <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>{{ spray_effectiveness_percentage }}</td>
                        {% calc_percentage chw.found chw.structures as found_coverage_percentage %}
                        <td class='numbers'>{{ found_coverage_percentage }}</td>
                        {% calc_percentage chw.visited_sprayed chw.found as spray_coverage_percentage %}
                        <td class='numbers'>{{ spray_coverage_percentage }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>{% trans "Not in Health Facility" %}</td>
                    <td></td>
                    <td class='numbers'>{{ no_location.found|default_if_none:"0"|intcomma }}</td>
                    <td class='numbers'>{{ no_location.sprayed|default_if_none:"0"|intcomma }}</td>
                    {% if no_location.sprayed and no_location.found %}
                        {% calc_percentage no_location.sprayed no_location.found as spray_effectiveness_percentage %}
                        <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>{{ spray_effectiveness_percentage }}</td>
                    {% else %}
                        <td class='numbers'></td>
                    {% endif %}
                    <td class='numbers'></td>
                    <td class='numbers'></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</a></td>
                    <td class='numbers'>{{ chw_totals.structures|intcomma }}</td>
                    <td class='numbers'>{{ chw_totals.visited_total|intcomma }}</td>
                    <td class='numbers'>{{ chw_totals.visited_sprayed|intcomma }} </td>
                    {% calc_percentage chw_totals.visited_sprayed chw_totals.structures as spray_effectiveness_percentage %}
                    <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>
                        {{ spray_effectiveness_percentage }}</td>
                    {% calc_percentage chw_totals.visited_total chw_totals.structures as found_coverage_percentage %}
                    <td class='numbers'>{{ found_coverage_percentage }}</td>
                    {% calc_percentage chw_totals.visited_sprayed chw_totals.found as spray_coverage_percentage %}
                    <td class='numbers'>{{ spray_coverage_percentage }}</td>
                </tr>
            </tfoot>
        </table>
        <p>* To sort a column, click on the column name</p>
        <p>* Health Facility Catchments not targeted for Reactive IRS display 0 structures on the ground</p>

        {% include 'definitions-and-conditions.html' %}
    </div>
</div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static "js/jquery-1.11.3.min.js" %}"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('table').DataTable({
                "paging": false,
            });
        } );
    </script>
{% endblock %}

mspray/apps/reactive/irs/templates/reactive_irs/map.html
{% extends 'home/base.html' %}

{% load staticfiles %}

{% block styles %}
    {{ block.super }}
        <link href='{% static "css/L.Control.Locate.min.css" %}' rel='stylesheet' />
{% endblock %}

{% block main_menu %}
    {% include 'reactive_irs/menu_list.html' %}
{% endblock %}

{% block spray_dates  %}
    <li class="dropdown" id="spray_date_picker">
        <a href="#" class="dropdown-toggle"
            data-toggle="dropdown">
            <span class="sprayday_label">Date: {{ spray_date }}</span>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" id="spraydays_list">
        {% for day in target_data.spray_dates %}
            <li>
                {% if object.level == "ta" %}
                <a href="{% url 'reactive_irs:target_area_map' object.parent.pk object.pk  %}?spray_date={{ day|date:'Y-m-d' }}">{{ day }}</a>
                {% elif object.parent %}
                <a href="{% url 'reactive_irs:chw_map' object.pk  %}?spray_date={{ day|date:'Y-m-d' }}">{{ day }}</a>
                {% else %}
                <a href="{% url 'reactive_irs:chw_list_map' object.pk  %}?spray_date={{ day|date:'Y-m-d' }}">{{ day }}</a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    </li>
{% endblock %}

{% block target_area_stats  %}
{% if object.parent %}
    <li class="active" id="target-area-stats-item"><a>Target Area Stats</a></li>
{% endif %}
{% endblock %}

{% block content %}
    <section class="info-panel">
        <div class="info-holder">
            <h4><span class="dist_label" id="target-area-label"> </span></h4>

            <div>
                <dl class="dl-horizontal" id="target-area-stats-structures">
                </dl>
            </div>
            <hr>
            <div>
                <dl class="dl-horizontal" id="target-area-stats">
                </dl>
            </div>
            <hr>
            <div>
                <dl class="dl-horizontal" id="target-area-stats">
                {% if sprayed_duplicates or not_sprayed_duplicates  %}
                <p>Some structures were selected more than once.<br />
                    <a id="sprayed-duplicates" style="color: white; font-weight: 600" href="#">Show duplicates</a>
                </p>
                {% endif %}
                {% if sprayed_duplicates %}
                    <dt>{{ sprayed_duplicates }}</dt>
                    <dd>Sprayed Duplicates</dd>
                {% endif %}
                {% if not_sprayed_duplicates %}
                    <dt>{{ not_sprayed_duplicates }}</dt>
                    <dd>Not Sprayed Duplicates</dd>
                {% endif %}
                {% if not sprayed_duplicates and not not_sprayed_duplicates  %}
                <p>No structures were selected more than once.</p>
                {% endif %}
                </dl>
            </div>
            <hr>
            <div id="not-sprayed-reasons">
                <p>Not Sprayed Reasons</p>
                <dl class="dl-horizontal" id="target-area-stats-not-sprayed"></dl>
            </div>
            <hr>
            <div>
                <dl class="dl-horizontal" id="target-area-stats">
                    <input type='button' class="btn btn-default btn-xs" onClick='previousStructure();' id='show-previous-structure' value='Previous Structure' data-toggle="tooltip" data-placement="bottom" title="No Spray Data"/>
                    <input type='button' class="btn btn-default btn-xs" onClick='nextStructure();' id='show-next-structure' value='Next Structure' data-toggle="tooltip" data-placement="bottom" title="No Spray Data" />
                </dl>
            </div>
        </div>
    </section>

    <div id="map"></div>

    <div id="map-legend">

        <h2><span class="day_label">Spray Coverage</span></h2>
        <div class="big" style="text-align:center">
            <div class="circle-holder">
                <div id="circle-progress"> </div>
                <p class="circle-text-p" id="progress-label">Sprayed</p>
                <p class="circle-text-p numbers" id="progress-ratio"></p>
            </div>
        </div>

        <div class="legend medium clearfix">
            <div class="circle-holder">
                <div id="found-coverage"> </div>
                <p class="circle-text-p" id="found-label">Found Coverage</p>
                <p class="circle-text-p numbers" id="found-ratio"></p>
            </div>
        </div>

        <div class="legend medium clearfix">
            <div class="circle-holder">
                <div id="spray-coverage"> </div>
                <p class="circle-text-p" id="sprayed-label">Spray Success Rate</p>
                <p class="circle-text-p numbers" id="sprayed-ratio"></p>
            </div>
        </div>

    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src='https://api.tiles.mapbox.com/mapbox.js/v2.2.0/mapbox.js'></script>
    <script src="https://maps.google.com/maps/api/js?key={{ GOOGLE_API_KEY }}&v=3"></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-label/v0.2.1/leaflet.label.js'></script>
    <script src="{% static "js/L.Control.Locate.min.js" %}"></script>
    <script src="{% static "js/Google.js" %}"></script>
    <script src="{% static "js/Bing.js" %}"></script>
    <script src="{% static "js/circles.min.js" %}"></script>
    <script src="{% static "js/app-reactive_irs.js" %}"></script>

    <script type="text/javascript">
        var bounds = {{ target_data.bounds|safe }};
        var targetAreaData = {% if ta_geojson %} {{ ta_geojson|safe }} {% else %} undefined {% endif %};
        var hhData = {% if hh_geojson %} {{ hh_geojson|safe }} {% else %} undefined {% endif %};
        var notSprayableValue = {% if not_sprayable_value %} '{{ not_sprayable_value }}' {% else %} null {% endif %};
        var app = new App(undefined, targetAreaData, hhData, notSprayableValue);
        app.fitBounds(bounds);

        app.housesCount = {{ target_data.structures }};
        app.visitedTotal = {{ target_data.found }};
        app.visitedSprayed = {{ target_data.visited_sprayed }};
        app.visitedNotSprayed = {{ target_data.visited_not_sprayed }};
        app.visitedRefused = {{ target_data.visited_refused }};
        app.visitedOther = {{ target_data.visited_other }};
        app.WAS_SPRAYED_VALUE = '{{ WAS_SPRAYED_VALUE }}';
        app.WAS_NOT_SPRAYED_VALUE = '{{ WAS_NOT_SPRAYED_VALUE }}';
        app.REASONS = {{ not_sprayed_reasons|safe }};

        {% if sprayed_duplicates %}
        app.sprayedDuplicates = {{ sprayed_duplicates }};
        app.sprayedDuplicatesData = {{ sprayed_duplicates_data|safe }};
        app.notSprayedDuplicates = {{ not_sprayed_duplicates }};
        app.notSprayedDuplicatesData = {{ not_sprayed_duplicates_data|safe }};
        {% endif %}

        var spraypoints_url = "{{ request.scheme }}://{{ request.get_host }}{% url 'reactive_irs:sprayday-list' format='json' %}?target_area={{ object.pk}}&spray_date__lte={{ spray_date|date:'Y-m-d' }}";
        app.loadSprayPoints(spraypoints_url);
        app.loadTargetAreas([{% for ta in tas %}"{{ request.scheme }}://{{ request.get_host }}{% url 'reactive_irs:location-detail' pk=ta.pk format='geojson' %}"{% if not forloop.last %}, {% endif %}{% endfor %}]);

        var count = 0;
        function nextStructure() {
            if(app.sprayLayer !== undefined) {
                layers = app.sprayLayer.getLayers()
                var arrayLength = layers.length;
                if(count == arrayLength){
                   count = 0;
                }
                layers[count].openPopup();
                count++;
            } else {
                $('#show-next-structure').tooltip('show');
            }
        }
        function previousStructure() {
            if(app.sprayLayer !== undefined) {
                layers = app.sprayLayer.getLayers()
                var arrayLength = layers.length;
                layers[count].openPopup();
                if (count > 0) {
                    count--;
                }
            } else {
                $('#show-previous-structure').tooltip('show');
            }
        }

    </script>
{% endblock %}

mspray/apps/reactive/irs/templates/reactive_irs/menu_list.html
{% if district_list %}
<li class="dropdown">
    {% if object.level == "district" %}
        <a href="{% url 'reactive_irs:chw_list_map' object.pk %}" class="dropdown-toggle" data-toggle="dropdown">
            {{ object.name }}
            <b class="caret"></b>
        </a>
    {% else %}
        <a href="{% url 'reactive_irs:chw_list_map' district_list.0.pk %}" class="dropdown-toggle" data-toggle="dropdown">
            {{ district_list.0.name }}
            <b class="caret"></b>
        </a>
    {% endif %}
    <ul class="dropdown-menu" id="districts_list">
        {% for district in district_list %}
        <li><a href="{% url 'reactive_irs:chw_list_map' district.pk %}">{{ district.name }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endif %}
{% if chw_list %}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="dist_label">CHW: All</span>
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" id="sub_locations_list">
        {% for chw in chw_list %}
        <li><a href="{% url 'reactive_irs:chw_map' chw.pk %}">{{ chw.name }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endif %}