mspray/apps/reactive/irs/urls.py
"""urls module for Reactive IRS"""
from django.conf.urls import include
from django.urls import path

from rest_framework import routers

from mspray.apps.main.views import (
    districts,
    household,
    household_buffer,
    sprayday,
    target_area,
)
from mspray.apps.reactive.irs import performance
from mspray.apps.reactive.irs.views import (
    CHWListView,
    CHWLocationMapView,
    CHWTargetAreaListView,
    CHWTargetAreaMapView,
    CHWTargetAreaView,
    HomeView,
)

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path("", performance.DistrictPerfomanceView.as_view(), name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
    ],
    "mspray",
)

# pylint: disable=invalid-name
app_name = "reactive_irs"
urlpatterns = [
    path("", HomeView.as_view(), name="reactive_irs_home"),
    path("<int:pk>", CHWListView.as_view(), name="chw_list"),
    path("chw", CHWTargetAreaListView.as_view(), name="ta_list"),
    path("chw/<int:pk>", CHWTargetAreaView.as_view(), name="ta_list"),
    path("map/<int:pk>", CHWLocationMapView.as_view(), name="chw_list_map"),
    path("chw/map/<int:pk>", CHWLocationMapView.as_view(), name="chw_map"),
    path("api/", include(router.urls)),
    path(
        "chw/<int:district_pk>/<int:slug>",
        CHWTargetAreaMapView.as_view(),
        name="target_area_map",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
]

mspray/apps/reveal/urls.py
"""
reveal.urls module.
"""
from django.urls import path

from mspray.apps.reveal.views import add_spray_data_view

app_name = "reveal"  # pylint: disable=invalid-name

urlpatterns = [  # pylint: disable=invalid-name
    path("add-spray-data/", add_spray_data_view, name="add_spray_data")
]

mspray/urls.py
# -*- coding: utf-8 -*-
"""
Mspray urls module.
"""
import sys

from django.conf import settings
from django.conf.urls import include, static, url
from django.contrib import admin
from django.urls import path

from rest_framework import routers

from mspray.apps.alerts import urls as alerts_urls
from mspray.apps.main.views import directly_observed_spraying_form as dos_form
from mspray.apps.main.views import (
    districts, home, household, household_buffer, indicators, performance,
    spray_operator_daily, sprayday, target_area, user)
from mspray.apps.main.views.decision import DecisionView
from mspray.apps.main.views.mobilisation import MobilisationView
from mspray.apps.main.views.mopup import HealthFacilityMopUpView, MopUpView
from mspray.apps.main.views.sensitization_visit import SensitizationVisitView
from mspray.apps.main.views.sprayday import NoLocationSprayDayView
from mspray.apps.mda import urls as mda_urls
from mspray.apps.reactive.irs import urls as reactive_irs_urls
from mspray.apps.warehouse import urls as warehouse_urls

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

admin.autodiscover()

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path(
            "", performance.DistrictPerfomanceView.as_view(),
            name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
        path(
            "definitions-and-conditions",
            performance.DefinitionAndConditionView.as_view(),
            name="definitions-and-conditions",
        ),
    ],
    "mspray",
)

urlpatterns = [  # pylint: disable=invalid-name
    path("reactive/irs/", include(reactive_irs_urls,
                                  namespace="reactive_irs")),
    path("mda/", include(mda_urls, namespace="mda")),
    path("mda-round-2/", include(mda_urls, namespace="mda-2")),
    path("trials/", include("mspray.apps.trials.urls", namespace="trials")),
    path("api/alerts/", include(alerts_urls, namespace="alerts")),
    path("api/", include(router.urls)),
    path("", home.DistrictView.as_view(), name="index"),
    path("login", user.login, name="login"),
    path("logout", user.logout, name="logout"),
    path(
        "not-in-target-area/",
        NoLocationSprayDayView.as_view(),
        name="no_location_spray_effectiveness",
    ),
    path("warehouse/", include(warehouse_urls, namespace="warehouse")),
    path(r"<int:pk>", home.DistrictView.as_view(), name="district"),
    path(
        "<int:district_pk>/<int:slug>",
        home.TargetAreaView.as_view(),
        name="target_area",
    ),
    path("sprayareas", home.SprayAreaView.as_view(), name="sprayareas"),
    path(
        "detailed-sprayareas/",
        home.DetailedCSVView.as_view(),
        name="detailed_sprayareas",
    ),
    path(
        "weekly-report", home.WeeklyReportView.as_view(),
        name="weeklyreports"),
    path(
        "indicators/number_of_households",
        indicators.NumberOfHouseholdsIndicatorView.as_view(),
        name="number_of_housesholds",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
    path("reveal/", include("mspray.apps.reveal.urls", namespace="reveal")),
    path("admin/", admin.site.urls),
    path(
        "spray-operator-daily",
        spray_operator_daily.SprayOperatorDailyViewSet.as_view({
            "post": "create"
        }),
        name="spray-operator-daily",
    ),
    path(
        "directly-observed-spraying-form",
        dos_form.DirectlyObservedSprayingFormViewSet.as_view({
            "post": "create"
        }),
        name="directly-observed-spraying-form",
    ),
    path(
        "directly-observed-spraying",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="directly-observed-spraying",
    ),
    path(
        "directly-observed-spraying/<int:district>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-district",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-team-leader",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>/"
        "<int:spray_operator>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-spray-operator",
    ),
    path(
        "sensitization-visit",
        SensitizationVisitView.as_view(),
        name="sensitization-visit",
    ),
    path(
        "mobilisation-visit",
        MobilisationView.as_view(),
        name="mobilisation-visit"),
    path("decision-visit", DecisionView.as_view(), name="decision-visit"),
    path("mop-up", MopUpView.as_view(), name="mop-up"),
    path(
        "mop-up/<int:district>",
        HealthFacilityMopUpView.as_view(),
        name="mop-up"),
] + static.static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if (settings.DEBUG or TESTING) and "debug_toolbar" in settings.INSTALLED_APPS:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

mspray/apps/main/models/decision.py
# -*- coding:utf-8 -*-
"""
Decision model.
"""

from django.contrib.gis.db import models
from django.contrib.postgres.fields import JSONField

from mspray.apps.main.models.location import Location
from mspray.libs.common_tags import DATA_ID_FIELD, SPRAY_AREA_FIELD


class Decision(models.Model):
    """
    Decision model.
    """

    submission_id = models.PositiveIntegerField(unique=True)
    today = models.DateField()
    geom = models.PointField(srid=4326, null=True)
    data = JSONField()
    household = models.ForeignKey(
        "Household",
        on_delete=models.SET_NULL,
        related_name="decision_households",
        null=True,
    )
    spray_area = models.ForeignKey(
        "Location",
        on_delete=models.CASCADE,
        related_name="decision_spray_areas",
    )
    health_facility = models.ForeignKey(
        "Location",
        on_delete=models.CASCADE,
        related_name="decision_health_facilities",
    )
    district = models.ForeignKey(
        "Location", on_delete=models.CASCADE, related_name="decision_districts"
    )
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "main"


def create_decision_visit(data):
    """Creates a Decision record from a Spray Area Decision Form.
    """
    district = health_facility = spray_area = None
    submission_id = data.get(DATA_ID_FIELD)
    today = data.get("today")
    spray_area = data.get(SPRAY_AREA_FIELD)
    if spray_area:
        # get location by spray_area
        try:
            spray_area = Location.objects.get(name=spray_area, level="ta")
        except Location.DoesNotExist:
            spray_area = None
        else:
            district = spray_area.parent.parent
            health_facility = spray_area.parent

    return Decision.objects.create(
        data=data,
        submission_id=submission_id,
        district=district,
        health_facility=health_facility,
        spray_area=spray_area,
        today=today,
    )

mspray/apps/main/models/district.py
# -*- coding: utf-8 -*-
"""
District model.
"""
from django.contrib.gis.db import models


class District(models.Model):
    """
    District model.
    """
    district_name = models.CharField(max_length=255, db_index=1)
    houses = models.IntegerField(db_index=1)
    geom = models.MultiPolygonField(srid=4326)
    code = models.CharField(max_length=10, db_index=1)

    class Meta:
        app_label = 'main'

    def __str__(self):
        return self.district_name

mspray/apps/main/models/household.py
# -*- coding: utf-8 -*-
"""
Household model.
"""
from django.contrib.gis.db import models
from django.contrib.postgres.fields import JSONField


class Household(models.Model):
    """
    Household model.
    """

    hh_id = models.IntegerField(unique=True)
    geom = models.PointField(srid=4326)
    bgeom = models.PolygonField(srid=4326, null=True, blank=True)
    location = models.ForeignKey(
        "Location", default=1, on_delete=models.CASCADE
    )
    rhc = models.ForeignKey(
        "Location",
        db_index=True,
        null=True,
        related_name="household_rhc_set",
        on_delete=models.CASCADE,
    )
    district = models.ForeignKey(
        "Location",
        db_index=True,
        null=True,
        related_name="houshold_district_set",
        on_delete=models.CASCADE,
    )
    data = JSONField(default=dict)
    visited = models.NullBooleanField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    sprayable = models.NullBooleanField(null=True)

    class Meta:
        app_label = "main"

    def __str__(self):
        return str(self.hh_id)

    @classmethod
    def by_osmid(cls, osmid):
        """Return a houshold object with the matching osmid for hh_id."""
        try:
            return cls.objects.get(hh_id=osmid)
        except cls.DoesNotExist:
            return None

    def _set_parent_locations(self):
        if self.location:
            if self.rhc != self.location.parent:  # pylint: disable=no-member
                self.rhc = self.location.parent  # pylint: disable=no-member
            if self.district != self.rhc.parent:  # pylint: disable=no-member
                self.district = self.rhc.parent  # pylint: disable=no-member

    # pylint: disable=arguments-differ
    def save(self, *args, **kwargs):
        self._set_parent_locations()

        return super(Household, self).save(*args, **kwargs)


# Auto-generated `LayerMapping` dictionary for Household model
household_mapping = {  # pylint: disable=C0103
    "hh_id": "OBJECTID",
    "geom": "POINT",
}

mspray/apps/main/models/households_buffer.py
# -*- coding: utf-8 -*-
"""
HouseholdsBuffer model.
"""
# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models


class HouseholdsBuffer(models.Model):
    """
    HouseholdsBuffer model
    """

    location = models.ForeignKey("Location", on_delete=models.CASCADE)
    num_households = models.IntegerField(default=0)
    geom = models.PolygonField(srid=4326)

    class Meta:
        app_label = "main"

mspray/apps/main/models/osm.py
from django.contrib.gis.db import models
from django.contrib.postgres.fields import JSONField


class Node(models.Model):
    node_id = models.BigIntegerField(unique=True)
    version = models.IntegerField()
    changeset = models.IntegerField()
    user = models.CharField(max_length=50, null=True)
    timestamp = models.DateTimeField(null=True)
    geom = models.PointField(srid=4326, null=True)
    tags = JSONField(default={}, null=True)

    class Meta:
        app_label = 'main'


class Way(models.Model):
    way_id = models.BigIntegerField(unique=True)
    action = models.CharField(max_length=20, null=True)
    version = models.IntegerField()
    changeset = models.IntegerField()
    user = models.CharField(max_length=50, null=True)
    timestamp = models.DateTimeField(null=True)
    geom = models.PolygonField(srid=4326, null=True)
    tags = JSONField(default={}, null=True)

    class Meta:
        app_label = 'main'

mspray/apps/main/models/team_leader.py
# -*- coding: utf-8 -*-
"""
TeamLeader model.
"""
from django.contrib.gis.db import models


class TeamLeader(models.Model):
    """
    TeamLeader model.
    """

    code = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=255, db_index=1)
    location = models.ForeignKey(
        "Location", null=True, on_delete=models.CASCADE
    )
    data_quality_check = models.BooleanField(default=False)
    average_spray_quality_score = models.FloatField(default=0.0)

    class Meta:
        app_label = "main"

    def __str__(self):
        return "{}".format(self.name)

mspray/apps/main/views/decision.py
# -*- coding: utf-8 -*-
"""
Decision view.
"""

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from mspray.apps.main.models.decision import create_decision_visit


class DecisionView(APIView):
    """Decision viewset."""

    def post(self, request):
        """Handle a Decision submission."""
        create_decision_visit(request.data)
        return Response(status=status.HTTP_201_CREATED)

mspray/apps/main/views/districts.py
from django.db.models import Count
from rest_framework import viewsets


from mspray.apps.main.models import TargetArea
from mspray.apps.main.serializers.district import DistrictSerializer
from mspray.apps.main.serializers.target_area import TargetAreaSerializer


class DistrictViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = TargetArea.objects.filter(targeted=TargetArea.TARGETED_VALUE)\
        .values('district_name')\
        .annotate(num_target_areas=Count('district_name'))
    serializer_class = DistrictSerializer

    def get_serializer_class(self):
        district = self.request.query_params.get('district')

        if district:
            return TargetAreaSerializer

        return super(DistrictViewSet, self).get_serializer_class()

    def filter_queryset(self, queryset):
        district = self.request.query_params.get('district')

        if district:
            queryset = TargetArea.objects.filter(
                targeted=TargetArea.TARGETED_VALUE,
                district_name=district
            ).order_by('targetid', 'houses')

        return queryset

mspray/apps/main/views/errors.py
# -*- coding: utf-8 -*
"""Custom 404 view."""
from django.shortcuts import render


def error_404(request, *args, **argv):
    """Render custom template."""
    data = {}
    template_name = '404.html'
    response = render(request, template_name, data)
    response.status_code = 404
    return response

mspray/apps/main/templates/home/base.html
{% load humanize %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>mSpray - {{ site_name|capfirst }}</title>
        <meta name='viewport' content='user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height' />
        {% block styles %}
        <link href='https://api.tiles.mapbox.com/mapbox.js/v2.2.0/mapbox.css' rel='stylesheet' />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-label/v0.2.1/leaflet.label.css' rel='stylesheet' />
        <link href='{% static "css/bootstrap.min.css" %}' rel='stylesheet'/>
        <link href='{% static "css/icons.data.png.css" %}' rel='stylesheet'/>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
        <link href='{% static "css/main.css" %}' rel='stylesheet' />
        {% endblock %}
    </head>
    <body>
        {% block header %}
        <header class="navbar navbar-inverse" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#msp-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"> </span>
                        <span class="icon-bar"> </span>
                        <span class="icon-bar"> </span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="{% static "img/mSpray-logo.png" %}" alt="mspray" id="mspray-logo"> {{ site_name|capfirst }}</a>
                </div>
                {% block map-nav %}
                <div class="collapse navbar-collapse" id="msp-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" {% if not IS_MDA_LINK and not IS_MDA_2_LINK and not IS_REACTIVE_IRS_LINK %} style="background-color: green" {% endif %} data-toggle="dropdown">
                                <span>
                                    {% if not IS_MDA_LINK and not IS_MDA_2_LINK and performance_tables %}
                                        IRS: Performance
                                    {% elif not IS_MDA_LINK and not IS_MDA_2_LINK and directly_observed_spraying %}
                                        IRS: Directly Observed Spraying
                                    {% elif not IS_MDA_LINK and not IS_MDA_2_LINK and trials %}
                                        IRS: Trial Survey
                                    {% else %}
                                        IRS{% if not IS_MDA_LINK and not IS_MDA_2_LINK %}: Spray Effectiveness{% endif %}
                                    {% endif %}</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'index' %}">IRS: Spray Effectiveness</a></li>
                                <!-- <li role="separator" class="divider"></li> -->
                                {% if view.request.session.show_csv %}
                                    <li class="dropdown-header"><a href="{% url 'sprayareas' %}">IRS: All Spray Areas</a></li>
                                    <li class="dropdown-header"><a href="{% url 'sprayareas' %}?format=csv"> IRS: CSV: All Spray Areas</a></li>
                                    <li class="dropdown-header"><a href="{% url 'detailed_sprayareas' %}"> IRS: CSV: Detailed Spray Areas</a></li>
                                    <li class="dropdown-header"><a href="{% url 'weeklyreports' %}"> IRS: CSV: Weekly Reports</a></li>
                                {% endif %}
                                <li role="separator" class="divider"></li>
                                {% if not ENABLE_REVEAL %}
                                <li><a href="{% url 'performance:districts' %} ">IRS: Performance</a></li>
                                {% endif %}
                                {% if SHOW_DIRECTLY_OBSERVED %}
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'directly-observed-spraying' %} ">IRS: Directly Observed Spraying</a></li>
                                {% endif %}
                                {% if SHOW_TRIAL_SURVEY %}
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'trials:index' %}">IRS: Trial Survey</a></li>
                                {% endif %}
                                {% if not ENABLE_REVEAL %}
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'mop-up' %}">IRS: Mop-up</a></li>
                                <li role="separator" class="divider"></li>
                                {% endif %}
                                {% if view.request.session.show_csv %}
                                    <li ><a href="{% url 'logout' %}">Logout</a></li>
                                {% else %}
                                    <li ><a href="{% url 'login' %}">Login</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        {% include 'snippets/mda_menu.html' %}
                        {% include 'reactive_irs/snippets/reactive_irs_menu.html' %}
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% block main_menu %}
                        {% include 'home/district_list.html' %}
                        {% include 'home/target_areas_list.html' %}
                        {% endblock %}
                        {% block spray_dates  %}
                        {% endblock %}
                        {% block target_area_stats  %}
                        {% endblock %}
                    </ul>
                </div>
                {% endblock %}
            </div>
        </header>
        {% endblock %}
        <section id="content">
        {% block content %}

        {% endblock %}
        </section>
        <section id="scripts">
        {% block scripts %}
            <script src="{% static "js/jquery-1.11.3.min.js" %}"></script>
            <script src="{% static "js/bootstrap.min.js" %}"></script>
        {% endblock %}
        </section>
    </body>
</html>

mspray/apps/main/templates/home/error_404.html
{% extends 'home/base.html' %}

{% load staticfiles %}

{% block content %}

  <div class="text-wrapper" style="background-color: #342643">
    <div class="title" data-content="404">
        404
    </div>

    <div class="subtitle">
        Oops, the page you're looking for doesn't exist.
    </div>

    <div class="buttons">
        <a class="button" href="http://www.ajerez.es">Go to homepage</a>
    </div>
</div>
{% endblock %}

mspray/apps/main/templates/home/login.html
{% extends 'home/base.html' %}

{% load humanize %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <form action="/login" method="post">{% csrf_token %}
        {% if error %} <div class="alert alert-danger">{{ error }}</div>{% endif %}
        <div class="form-group{% if error %} has-error{% endif %}" >
            <label for="username1">Username</label>
            <input type="text" class="form-control" name="username1" id="username1" placeholder="Username">
        </div>
        <div class="form-group{% if error %} has-error{% endif %}">
            <label for="password1">Password</label>
            <input type="password" class="form-control" name="password1" id="password1" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-default">Login</button>
    </form>
</div>
{% endblock %}

mspray/apps/main/templates/home/sprayareas.html
{% extends 'home/base.html' %}

{% load humanize %}
{% load staticfiles %}
{% load performance_extras %}
{% load progress_extras %}

{% block content %}
<div class="container" id="district_table">
    <div "col-sm-12" id="table-container">
        <h1 id="district-name">
            All Spray Areas
        </h1>
        <table id="target_areas" class="table table-stripe">
            <thead>
                <tr>
                    <th>District</th>
                    <th>Health Centre</th>
                    <th>Target Area</th>
                    <th>Structures on ground</th>
                    <th>Found</th>
                    <th>Sprayed</th>
                    <th>Spray Effectiveness</th>
                    <th>Found coverage</th>
                    <th>Spray coverage</th>
                </tr>
            </thead>
            <tbody>
                {% for district in district_list %}
                    <tr>
                        <td class='numbers'>{{ district.district }}</td>
                        <td class='numbers'>{{ district.rhc }}</td>
                        <td>
                            <a href="{% url 'target_area' district.rhc_pk district.targetid %}">
                                <i class="fa fa-map"></i>
                                {{ district.district_name }}
                            </a>
                            </td>
                        </td>

                        <td class='numbers'>{{ district.structures|intcomma }}</td>
                        <td class='numbers'>{{ district.found|intcomma }}</td>
                        <td class='numbers'>{{ district.visited_sprayed|intcomma }} </td>
                        {% calc_percentage district.visited_sprayed district.structures as spray_effectiveness_percentage %}
                        <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>{{ spray_effectiveness_percentage }}</td>
                        {% calc_percentage district.found district.structures as found_coverage_percentage %}
                        <td class='numbers'>{{ found_coverage_percentage }}</td>
                        {% calc_percentage district.visited_sprayed district.found as spray_coverage_percentage %}
                        <td class='numbers'>{{ spray_coverage_percentage }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td class='numbers'>{{ district_totals.structures|intcomma }}</td>
                        <td class='numbers'>{{ district_totals.visited_total|intcomma }}</td>
                        <td class='numbers'>{{ district_totals.visited_sprayed|intcomma }} </td>
                        {% calc_percentage district_totals.visited_sprayed district_totals.structures as spray_effectiveness_percentage %}
                        <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>{{ spray_effectiveness_percentage }}</td>
                        {% calc_percentage district_totals.visited_total district_totals.structures as found_coverage_percentage %}
                        <td class='numbers'>{{ found_coverage_percentage }}</td>
                        {% calc_percentage district_totals.visited_sprayed district_totals.visited_total as spray_coverage_percentage %}
                        <td class='numbers'>{{ spray_coverage_percentage }}</td>
                </tr>
            </tfoot>
        </table>
        <!-- <p>* To sort a column, click on the column name</p> -->

        {% include 'definitions-and-conditions.html' %}
    </div>
</div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static "js/jquery-1.11.3.min.js" %}"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('table').DataTable({
                "paging": false,
            });
        } );
    </script>
{% endblock %}

mspray/apps/main/templates/home/target_areas_list.html
                        {% if target_areas %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle"
                               data-toggle="dropdown">
                                <span class="target_label">Target Area: {{ object.district_name }}</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <form action="/" method="post" class="form-inline" id="search_form">
                                        <input type="text" name="target_filter" class="target_filter form-control" placeholder="Search..."/>
                                    </form>
                                    <ul id="target_areas_list">
                                    {% for targetid in target_areas %}
                                        <li>
                                            <a href="{% url 'target_area' object.pk targetid  %}">{{ targetid }}</a>
                                        </li>
                                    {% endfor %}
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        {% endif %}