mspray/apps/mda/urls.py
# -*- coding: utf-8 -*-
"""MDA urls"""
from django.conf.urls import include
from django.urls import path, re_path

from rest_framework import routers

from mspray.apps.main.views import (
    districts,
    household,
    household_buffer,
    performance,
    sprayday,
    target_area,
)
from mspray.apps.main.views.mopup import HealthFacilityMopUpView, MopUpView
from mspray.apps.mda.views.index import MDALocationView, MDAView
from mspray.apps.mda.views.map import MapView
from mspray.apps.mda.views.spray_area import SprayAreaView

app_name = "mda"  # pylint: disable=invalid-name

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path(
            "",
            performance.MDADistrictPerfomanceView.as_view(),
            name="districts",
        ),
        path(
            "rhcs/<int:district_id>",
            performance.RHCPerformanceView.as_view(),
            name="rhcs",
        ),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:rhc_id>/summary",
            performance.MDASprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:rhc_id>/<int:spray_operator>/daily",
            performance.MDASprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
        path(
            "definitions-and-conditions",
            performance.DefinitionAndConditionView.as_view(),
            name="definitions-and-conditions",
        ),
    ],
    "mspray",
)

urlpatterns = [  # pylint: disable=invalid-name
    path("", MDAView.as_view(), name="index"),
    path("<int:location>", MDALocationView.as_view(), name="location"),
    path("<int:district_pk>/<int:slug>", MapView.as_view(), name="spray-area"),
    path("performance/", include(performance_urls, namespace="performance")),
    path("api/", include(router.urls)),
    path("sprayareas", SprayAreaView.as_view(), name="sprayareas"),
    re_path(
        r"^sprayareas\.(?P<format>[csv]{3})$",
        SprayAreaView.as_view(),
        name="sprayareas-csv",
    ),
    path("mop-up", MopUpView.as_view(), name="mop-up"),
    path(
        "mop-up/<int:district>",
        HealthFacilityMopUpView.as_view(),
        name="mop-up",
    ),
]

mspray/apps/reactive/irs/urls.py
"""urls module for Reactive IRS"""
from django.conf.urls import include
from django.urls import path

from rest_framework import routers

from mspray.apps.main.views import (
    districts,
    household,
    household_buffer,
    sprayday,
    target_area,
)
from mspray.apps.reactive.irs import performance
from mspray.apps.reactive.irs.views import (
    CHWListView,
    CHWLocationMapView,
    CHWTargetAreaListView,
    CHWTargetAreaMapView,
    CHWTargetAreaView,
    HomeView,
)

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path("", performance.DistrictPerfomanceView.as_view(), name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
    ],
    "mspray",
)

# pylint: disable=invalid-name
app_name = "reactive_irs"
urlpatterns = [
    path("", HomeView.as_view(), name="reactive_irs_home"),
    path("<int:pk>", CHWListView.as_view(), name="chw_list"),
    path("chw", CHWTargetAreaListView.as_view(), name="ta_list"),
    path("chw/<int:pk>", CHWTargetAreaView.as_view(), name="ta_list"),
    path("map/<int:pk>", CHWLocationMapView.as_view(), name="chw_list_map"),
    path("chw/map/<int:pk>", CHWLocationMapView.as_view(), name="chw_map"),
    path("api/", include(router.urls)),
    path(
        "chw/<int:district_pk>/<int:slug>",
        CHWTargetAreaMapView.as_view(),
        name="target_area_map",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
]

mspray/apps/reveal/urls.py
"""
reveal.urls module.
"""
from django.urls import path

from mspray.apps.reveal.views import add_spray_data_view

app_name = "reveal"  # pylint: disable=invalid-name

urlpatterns = [  # pylint: disable=invalid-name
    path("add-spray-data/", add_spray_data_view, name="add_spray_data")
]

mspray/urls.py
# -*- coding: utf-8 -*-
"""
Mspray urls module.
"""
import sys

from django.conf import settings
from django.conf.urls import include, static, url
from django.contrib import admin
from django.urls import path

from rest_framework import routers

from mspray.apps.alerts import urls as alerts_urls
from mspray.apps.main.views import directly_observed_spraying_form as dos_form
from mspray.apps.main.views import (
    districts, home, household, household_buffer, indicators, performance,
    spray_operator_daily, sprayday, target_area, user)
from mspray.apps.main.views.decision import DecisionView
from mspray.apps.main.views.mobilisation import MobilisationView
from mspray.apps.main.views.mopup import HealthFacilityMopUpView, MopUpView
from mspray.apps.main.views.sensitization_visit import SensitizationVisitView
from mspray.apps.main.views.sprayday import NoLocationSprayDayView
from mspray.apps.mda import urls as mda_urls
from mspray.apps.reactive.irs import urls as reactive_irs_urls
from mspray.apps.warehouse import urls as warehouse_urls

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

admin.autodiscover()

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path(
            "", performance.DistrictPerfomanceView.as_view(),
            name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
        path(
            "definitions-and-conditions",
            performance.DefinitionAndConditionView.as_view(),
            name="definitions-and-conditions",
        ),
    ],
    "mspray",
)

urlpatterns = [  # pylint: disable=invalid-name
    path("reactive/irs/", include(reactive_irs_urls,
                                  namespace="reactive_irs")),
    path("mda/", include(mda_urls, namespace="mda")),
    path("mda-round-2/", include(mda_urls, namespace="mda-2")),
    path("trials/", include("mspray.apps.trials.urls", namespace="trials")),
    path("api/alerts/", include(alerts_urls, namespace="alerts")),
    path("api/", include(router.urls)),
    path("", home.DistrictView.as_view(), name="index"),
    path("login", user.login, name="login"),
    path("logout", user.logout, name="logout"),
    path(
        "not-in-target-area/",
        NoLocationSprayDayView.as_view(),
        name="no_location_spray_effectiveness",
    ),
    path("warehouse/", include(warehouse_urls, namespace="warehouse")),
    path(r"<int:pk>", home.DistrictView.as_view(), name="district"),
    path(
        "<int:district_pk>/<int:slug>",
        home.TargetAreaView.as_view(),
        name="target_area",
    ),
    path("sprayareas", home.SprayAreaView.as_view(), name="sprayareas"),
    path(
        "detailed-sprayareas/",
        home.DetailedCSVView.as_view(),
        name="detailed_sprayareas",
    ),
    path(
        "weekly-report", home.WeeklyReportView.as_view(),
        name="weeklyreports"),
    path(
        "indicators/number_of_households",
        indicators.NumberOfHouseholdsIndicatorView.as_view(),
        name="number_of_housesholds",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
    path("reveal/", include("mspray.apps.reveal.urls", namespace="reveal")),
    path("admin/", admin.site.urls),
    path(
        "spray-operator-daily",
        spray_operator_daily.SprayOperatorDailyViewSet.as_view({
            "post": "create"
        }),
        name="spray-operator-daily",
    ),
    path(
        "directly-observed-spraying-form",
        dos_form.DirectlyObservedSprayingFormViewSet.as_view({
            "post": "create"
        }),
        name="directly-observed-spraying-form",
    ),
    path(
        "directly-observed-spraying",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="directly-observed-spraying",
    ),
    path(
        "directly-observed-spraying/<int:district>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-district",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-team-leader",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>/"
        "<int:spray_operator>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-spray-operator",
    ),
    path(
        "sensitization-visit",
        SensitizationVisitView.as_view(),
        name="sensitization-visit",
    ),
    path(
        "mobilisation-visit",
        MobilisationView.as_view(),
        name="mobilisation-visit"),
    path("decision-visit", DecisionView.as_view(), name="decision-visit"),
    path("mop-up", MopUpView.as_view(), name="mop-up"),
    path(
        "mop-up/<int:district>",
        HealthFacilityMopUpView.as_view(),
        name="mop-up"),
] + static.static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if (settings.DEBUG or TESTING) and "debug_toolbar" in settings.INSTALLED_APPS:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

mspray/apps/mda/views/index.py
# -*- coding: utf-8 -*-
"""MDA view module.
"""
from django.shortcuts import get_object_or_404
from django.views.generic import ListView

from mspray.apps.main.definitions import DEFINITIONS
from mspray.apps.main.models import Location


class MDAView(ListView):
    """MDA view."""

    template_name = "mda-location.html"
    queryset = Location.objects.filter(level="district", target=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["site_name"] = "MDA"
        context["ENABLE_MDA"] = True

        # show definitions legend for mda
        context.update(DEFINITIONS.get("mda", {}))

        return context


class MDALocationView(ListView):
    """MDA Location view."""

    template_name = "mda-location.html"
    queryset = Location.objects.filter(target=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["site_name"] = "MDA"
        context["mda_location"] = get_object_or_404(
            Location, pk=self.kwargs["location"], target=True
        )
        context["ENABLE_MDA"] = True

        # show definitions legend for mda
        context.update(DEFINITIONS.get("mda", {}))

        return context

    def get_queryset(self):
        return super().get_queryset().filter(parent_id=self.kwargs["location"])

mspray/apps/mda/views/map.py
# -*- coding: utf-8 -*-
"""Map views"""
import json

from django.conf import settings
from django.views.generic import DetailView

from mspray.apps.main.mixins import SiteNameMixin
from mspray.apps.main.models import Location
from mspray.apps.main.query import get_location_qs
from mspray.apps.main.serializers.target_area import (
    GeoTargetAreaSerializer,
    TargetAreaQuerySerializer,
    TargetAreaSerializer,
    count_duplicates,
    get_duplicates,
)
from mspray.apps.main.utils import get_location_dict, parse_spray_date
from mspray.apps.main.views.target_area import (
    TargetAreaHouseholdsViewSet,
    TargetAreaViewSet,
)


class MapView(SiteNameMixin, DetailView):
    """Map View"""

    template_name = "map.html"
    model = Location
    slug_field = "pk"

    def get_queryset(self):

        return get_location_qs(super(MapView, self).get_queryset())

    def get_context_data(self, **kwargs):
        context = super(MapView, self).get_context_data(**kwargs)
        serializer_class = (
            TargetAreaQuerySerializer
            if settings.SITE_NAME == "namibia"
            else TargetAreaSerializer
        )
        location = context["object"]
        if location.level == "RHC":
            location = get_location_qs(
                Location.objects.filter(pk=location.pk), "RHC"
            ).first()
        serializer = serializer_class(
            location, context={"request": self.request}
        )
        context["target_data"] = serializer.data
        spray_date = parse_spray_date(self.request)
        if spray_date:
            context["spray_date"] = spray_date
        if settings.MSPRAY_SPATIAL_QUERIES or context["object"].geom:
            response = TargetAreaViewSet.as_view({"get": "retrieve"})(
                self.request, pk=context["object"].pk, format="geojson"
            )
            response.render()
            context["not_sprayable_value"] = getattr(
                settings, "NOT_SPRAYABLE_VALUE", "noteligible"
            )
            context["ta_geojson"] = response.content.decode()
            bgeom = settings.HH_BUFFER and settings.OSM_SUBMISSIONS

            if self.object.level in ["district", "RHC"]:
                data = GeoTargetAreaSerializer(
                    get_location_qs(
                        self.object.location_set.all(), self.object.level
                    ),
                    many=True,
                    context={"request": self.request},
                ).data
                context["hh_geojson"] = json.dumps(data)
            else:
                loc = context["object"]
                hhview = TargetAreaHouseholdsViewSet.as_view(
                    {"get": "retrieve"}
                )
                response = hhview(
                    self.request,
                    pk=loc.pk,
                    bgeom=bgeom,
                    spray_date=spray_date,
                    format="geojson",
                )
                response.render()
                context["hh_geojson"] = response.content.decode()
                sprayed_duplicates = list(
                    get_duplicates(loc, True, spray_date)
                )
                not_sprayed_duplicates = list(
                    get_duplicates(loc, False, spray_date)
                )
                context["sprayed_duplicates_data"] = json.dumps(
                    sprayed_duplicates
                )
                context["sprayed_duplicates"] = count_duplicates(
                    loc, True, spray_date
                )
                context["not_sprayed_duplicates_data"] = json.dumps(
                    not_sprayed_duplicates
                )
                context["not_sprayed_duplicates"] = count_duplicates(
                    loc, False
                )

        context["districts"] = (
            Location.objects.filter(parent=None)
            .values_list("id", "code", "name")
            .order_by("name")
        )

        context.update({"map_menu": True})
        context.update(get_location_dict(self.object.pk))
        context["not_sprayed_reasons"] = json.dumps(
            settings.MSPRAY_UNSPRAYED_REASON_OTHER
        )

        return context

mspray/apps/mda/templates/mda-location.html
{% extends 'home/base.html' %}

{% load humanize %}
{% load staticfiles %}
{% load performance_extras %}
{% load progress_extras %}
{% load i18n %}

{% block content %}
<div class="container" id="district_table">
    <div "col-sm-12" id="table-container">
        <h1 id="district-name">
            {% if mda_location.level == 'district' %}
            District:
            {% elif mda_location.level == 'RHC' %}
            Health Facility Catchment:
            {% endif %}

            {% if mda_location %}
            {{ mda_location.name }}
            {% if mda_location.level == 'district' %}
            <a href="{% url 'mda:spray-area' mda_location.pk mda_location.pk %}">
            {% else %}
            <a href="{% url 'mda:spray-area' mda_location.parent_id mda_location.pk %}">
            {% endif %}
                <i class="fa fa-map"></i>
            </a>
            {% else %}
            All
            {% endif%}
        </h1>
        <table id="target_areas" class="table table-stripe">
            <thead>
                {% if not mda_location or mda_location.level != 'RHC' %}
                <tr>
                    <th rowspan="2">{% if mda_location %} Health Facility {% else %} District {% endif%}</th>
                    <th rowspan="2">Eligible Areas</th>
                    <th colspan="2">MDA Areas Reached<sup title=""></sup></th>
                    <th colspan="2">MDA Areas Covered Effectively<sup title=""></sup></th>
                    <th rowspan="2">Community Readiness</th>
                    <th rowspan="2">Mobilised</th>
                </tr>
                <tr>
                    <th>Number</th>
                    <th>%</th>
                    <th>Number</th>
                    <th>%</th>
                </tr>
                {% else %}
                <tr>
                    <th>Target Area</th>
                    <th>Eligible Structures on the Ground</th>
                    <th>Structures Found</th>
                    <th>Structures Received</th>
                    <th>Structures Received Coverage</th>
                    <th>Structures Found Coverage</th>
                    <th>Structures Received Success Rate</th>
                    <th>Population Received Success Rate</th>
                    <th>Community Ready?</th>
                    <th>Mobilised?</th>
                </tr>
                {% endif%}
            </thead>
            <tbody>
            {% if not mda_location or mda_location.level != 'RHC' %}
                {% for location in object_list %}
                    <tr>
                        <td>
                            {% if location.parent_id %}
                            <a href="{% url 'mda:spray-area' location.parent_id location.pk %}">
                            {% else %}
                            <a href="{% url 'mda:spray-area' location.pk location.pk %}">
                            {% endif %}
                                <i class="fa fa-map"></i>
                            </a>
                            <a href="{% url 'mda:location' location.pk  %}">
                                {{ location.name }}
                            </a>
                        </td>
                        <td class='numbers'>
                            {% if location.level != 'ta' %}
                            {{location.mda_spray_areas }}
                            {% else %}
                            {{ location.structures|intcomma }}
                            {% endif %}
                        </td>
                        <td class='numbers'>{{ location.mda_spray_areas_found|intcomma }}</td>
                        <td class='numbers'>
                            {% if site_name != 'namibia' %}
                            {% percentage location.mda_spray_areas_found location.mda_spray_areas %}
                            {% endif %}</td>
                        <td class='numbers'>{{ location.mda_spray_areas_received|intcomma }}</td>
                        {% calc_percentage location.mda_spray_areas_received location.mda_spray_areas_found as calculated_percentage %}
                        <td class='numbers {{ calculated_percentage|sprayed_effectively_color }}'>{{ calculated_percentage }}</td>
                        <td class=''>{{ location.sensitized }}</td>
                        <td class=''>{{ location.mobilised }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                {% for location in object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'mda:spray-area' location.parent_id location.pk %}">
                                <i class="fa fa-map"></i>
                                {{ location.name }}
                            </a>
                            </td>
                        </td>

                        <td class='numbers'>{{ location.structures_on_ground|intcomma }}</td>
                        <td class='numbers'>{{ location.mda_found|intcomma }}</td>
                        <td class='numbers'>{{ location.visited_sprayed|intcomma }} </td>
                        {% calc_percentage location.visited_sprayed location.structures_on_ground as spray_effectiveness_percentage %}
                        <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>
                            {{ spray_effectiveness_percentage }}
                        </td>
                        {% calc_percentage location.mda_found location.structures_on_ground as found_coverage_percentage %}
                        <td class='numbers'>{{ found_coverage_percentage }}</td>
                        {% calc_percentage location.visited_sprayed location.mda_found as spray_coverage_percentage %}
                        <td class='numbers'>{{ spray_coverage_percentage }}</td>
                        <td class='numbers'>
                            {% calc_percentage location.population_treatment location.population_eligible as population_percentage %}
                            {{ population_percentage }}
                        </td>
                        <td class=''>{{ location.sensitized }}</td>
                        <td class=''>{{ location.mobilised }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>{% trans "Not in Targeted Area" %}</td>
                    <td class='numbers'></td>
                    <td class='numbers'>{{ no_location.found|default_if_none:"0"|intcomma }}</td>
                    <td class='numbers'>{{ no_location.sprayed|default_if_none:"0"|intcomma }}</td>
                    {% if no_location.sprayed and no_location.found %}
                     {% calc_percentage no_location.sprayed no_location.found as spray_effectiveness_percentage %}
                     <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>{{ spray_effectiveness_percentage }}</td>
                    {% else %}
                        <td class='numbers'></td>
                    {% endif %}
                    <td class='numbers'></td>
                    <td class='numbers'></td>
                    <td class='numbers'></td>
                    <td class=''></td>
                    <td class=''></td>
                </tr>
            {% endif%}
            </tbody>
            {% if not mda_location or mda_location.level != 'RHC' %}
            <tfoot>
                <tr>
                    <td>Total</a></td>
                    <td class='numbers'>{{ mda_location.mda_spray_areas|intcomma }}</td>
                    <td class='numbers'>{{ mda_location.mda_spray_areas_found|intcomma }}</td>
                    {% calc_percentage mda_location.mda_spray_areas_found mda_location.mda_spray_areas as spray_effectiveness_percentage %}
                    <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>
                        {{ spray_effectiveness_percentage }}
                    </td>
                    {% calc_percentage mda_location.mda_spray_areas_found mda_location.structures_on_ground as found_coverage_percentage %}
                    <td class='numbers'>{{ found_coverage_percentage }}</td>
                    {% calc_percentage mda_location.mda_spray_areas_received mda_location.mda_spray_areas_found as spray_coverage_percentage %}
                    <td class='numbers'>{{ spray_coverage_percentage }}</td>
                    <td class='numbers'></td>
                    <td class='numbers'></td>
                </tr>
            </tfoot>
            {% else %}
            <tfoot>
                <tr>
                    <td>Total</a></td>
                    <td class='numbers'>{{ mda_location.structures_on_ground|intcomma }}</td>
                    <td class='numbers'>{{ mda_location.mda_found|intcomma }}</td>
                    <td class='numbers'>{{ mda_location.visited_sprayed|intcomma }} </td>
                    {% calc_percentage mda_location.visited_sprayed mda_location.structures_on_ground as spray_effectiveness_percentage %}
                    <td class='numbers {{ spray_effectiveness_percentage|sprayed_effectively_color }}'>
                        {{ spray_effectiveness_percentage }}
                    </td>
                    {% calc_percentage mda_location.mda_found mda_location.structures_on_ground as found_coverage_percentage %}
                    <td class='numbers'>{{ found_coverage_percentage }}</td>
                    {% calc_percentage mda_location.visited_sprayed mda_location.mda_found as spray_coverage_percentage %}
                    <td class='numbers'>{{ spray_coverage_percentage }}</td>
                    <td class='numbers'></td>
                    <td class=''></td>
                    <td class=''></td>
                </tr>
            </tfoot>
            {% endif%}
        </table>
        <p>* To sort a column, click on the column name</p>

        {% include 'definitions-and-conditions.html' %}
    </div>
</div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static "js/jquery-1.11.3.min.js" %}"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('table').DataTable({
                "paging": false,
            });
        } );
    </script>
{% endblock %}