mspray/apps/reactive/irs/urls.py
"""urls module for Reactive IRS"""
from django.conf.urls import include
from django.urls import path

from rest_framework import routers

from mspray.apps.main.views import (
    districts,
    household,
    household_buffer,
    sprayday,
    target_area,
)
from mspray.apps.reactive.irs import performance
from mspray.apps.reactive.irs.views import (
    CHWListView,
    CHWLocationMapView,
    CHWTargetAreaListView,
    CHWTargetAreaMapView,
    CHWTargetAreaView,
    HomeView,
)

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path("", performance.DistrictPerfomanceView.as_view(), name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
    ],
    "mspray",
)

# pylint: disable=invalid-name
app_name = "reactive_irs"
urlpatterns = [
    path("", HomeView.as_view(), name="reactive_irs_home"),
    path("<int:pk>", CHWListView.as_view(), name="chw_list"),
    path("chw", CHWTargetAreaListView.as_view(), name="ta_list"),
    path("chw/<int:pk>", CHWTargetAreaView.as_view(), name="ta_list"),
    path("map/<int:pk>", CHWLocationMapView.as_view(), name="chw_list_map"),
    path("chw/map/<int:pk>", CHWLocationMapView.as_view(), name="chw_map"),
    path("api/", include(router.urls)),
    path(
        "chw/<int:district_pk>/<int:slug>",
        CHWTargetAreaMapView.as_view(),
        name="target_area_map",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
]

mspray/apps/reveal/urls.py
"""
reveal.urls module.
"""
from django.urls import path

from mspray.apps.reveal.views import add_spray_data_view

app_name = "reveal"  # pylint: disable=invalid-name

urlpatterns = [  # pylint: disable=invalid-name
    path("add-spray-data/", add_spray_data_view, name="add_spray_data")
]

mspray/urls.py
# -*- coding: utf-8 -*-
"""
Mspray urls module.
"""
import sys

from django.conf import settings
from django.conf.urls import include, static, url
from django.contrib import admin
from django.urls import path

from rest_framework import routers

from mspray.apps.alerts import urls as alerts_urls
from mspray.apps.main.views import directly_observed_spraying_form as dos_form
from mspray.apps.main.views import (
    districts, home, household, household_buffer, indicators, performance,
    spray_operator_daily, sprayday, target_area, user)
from mspray.apps.main.views.decision import DecisionView
from mspray.apps.main.views.mobilisation import MobilisationView
from mspray.apps.main.views.mopup import HealthFacilityMopUpView, MopUpView
from mspray.apps.main.views.sensitization_visit import SensitizationVisitView
from mspray.apps.main.views.sprayday import NoLocationSprayDayView
from mspray.apps.mda import urls as mda_urls
from mspray.apps.reactive.irs import urls as reactive_irs_urls
from mspray.apps.warehouse import urls as warehouse_urls

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

admin.autodiscover()

router = routers.DefaultRouter(trailing_slash=False)  # pylint: disable=C0103

router.register(r"buffers", household_buffer.HouseholdBufferViewSet)
router.register(r"districts", districts.DistrictViewSet, "district")
router.register(r"households", household.HouseholdViewSet)
router.register(r"spraydays", sprayday.SprayDayViewSet)
router.register(r"targetareas", target_area.TargetAreaViewSet)

performance_urls = (  # pylint: disable=C0103
    [
        path(
            "", performance.DistrictPerfomanceView.as_view(),
            name="districts"),
        path(
            "team-leaders/<int:slug>",
            performance.TeamLeadersPerformanceView.as_view(),
            name="team-leaders",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/summary",
            performance.SprayOperatorSummaryView.as_view(),
            name="spray-operator-summary",
        ),
        path(
            "spray-operators/<int:slug>/<int:team_leader>/"
            "<int:spray_operator>/daily",
            performance.SprayOperatorDailyView.as_view(),
            name="spray-operator-daily",
        ),
        path(
            "definitions-and-conditions",
            performance.DefinitionAndConditionView.as_view(),
            name="definitions-and-conditions",
        ),
    ],
    "mspray",
)

urlpatterns = [  # pylint: disable=invalid-name
    path("reactive/irs/", include(reactive_irs_urls,
                                  namespace="reactive_irs")),
    path("mda/", include(mda_urls, namespace="mda")),
    path("mda-round-2/", include(mda_urls, namespace="mda-2")),
    path("trials/", include("mspray.apps.trials.urls", namespace="trials")),
    path("api/alerts/", include(alerts_urls, namespace="alerts")),
    path("api/", include(router.urls)),
    path("", home.DistrictView.as_view(), name="index"),
    path("login", user.login, name="login"),
    path("logout", user.logout, name="logout"),
    path(
        "not-in-target-area/",
        NoLocationSprayDayView.as_view(),
        name="no_location_spray_effectiveness",
    ),
    path("warehouse/", include(warehouse_urls, namespace="warehouse")),
    path(r"<int:pk>", home.DistrictView.as_view(), name="district"),
    path(
        "<int:district_pk>/<int:slug>",
        home.TargetAreaView.as_view(),
        name="target_area",
    ),
    path("sprayareas", home.SprayAreaView.as_view(), name="sprayareas"),
    path(
        "detailed-sprayareas/",
        home.DetailedCSVView.as_view(),
        name="detailed_sprayareas",
    ),
    path(
        "weekly-report", home.WeeklyReportView.as_view(),
        name="weeklyreports"),
    path(
        "indicators/number_of_households",
        indicators.NumberOfHouseholdsIndicatorView.as_view(),
        name="number_of_housesholds",
    ),
    path("performance/", include(performance_urls, namespace="performance")),
    path("reveal/", include("mspray.apps.reveal.urls", namespace="reveal")),
    path("admin/", admin.site.urls),
    path(
        "spray-operator-daily",
        spray_operator_daily.SprayOperatorDailyViewSet.as_view({
            "post": "create"
        }),
        name="spray-operator-daily",
    ),
    path(
        "directly-observed-spraying-form",
        dos_form.DirectlyObservedSprayingFormViewSet.as_view({
            "post": "create"
        }),
        name="directly-observed-spraying-form",
    ),
    path(
        "directly-observed-spraying",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="directly-observed-spraying",
    ),
    path(
        "directly-observed-spraying/<int:district>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-district",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-team-leader",
    ),
    path(
        "directly-observed-spraying/<int:district>/<int:team_leader>/"
        "<int:spray_operator>",
        dos_form.DirectlyObservedSprayingView.as_view(),
        name="dos-spray-operator",
    ),
    path(
        "sensitization-visit",
        SensitizationVisitView.as_view(),
        name="sensitization-visit",
    ),
    path(
        "mobilisation-visit",
        MobilisationView.as_view(),
        name="mobilisation-visit"),
    path("decision-visit", DecisionView.as_view(), name="decision-visit"),
    path("mop-up", MopUpView.as_view(), name="mop-up"),
    path(
        "mop-up/<int:district>",
        HealthFacilityMopUpView.as_view(),
        name="mop-up"),
] + static.static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if (settings.DEBUG or TESTING) and "debug_toolbar" in settings.INSTALLED_APPS:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

mspray/apps/main/models/decision.py
# -*- coding:utf-8 -*-
"""
Decision model.
"""

from django.contrib.gis.db import models
from django.contrib.postgres.fields import JSONField

from mspray.apps.main.models.location import Location
from mspray.libs.common_tags import DATA_ID_FIELD, SPRAY_AREA_FIELD


class Decision(models.Model):
    """
    Decision model.
    """

    submission_id = models.PositiveIntegerField(unique=True)
    today = models.DateField()
    geom = models.PointField(srid=4326, null=True)
    data = JSONField()
    household = models.ForeignKey(
        "Household",
        on_delete=models.SET_NULL,
        related_name="decision_households",
        null=True,
    )
    spray_area = models.ForeignKey(
        "Location",
        on_delete=models.CASCADE,
        related_name="decision_spray_areas",
    )
    health_facility = models.ForeignKey(
        "Location",
        on_delete=models.CASCADE,
        related_name="decision_health_facilities",
    )
    district = models.ForeignKey(
        "Location", on_delete=models.CASCADE, related_name="decision_districts"
    )
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "main"


def create_decision_visit(data):
    """Creates a Decision record from a Spray Area Decision Form.
    """
    district = health_facility = spray_area = None
    submission_id = data.get(DATA_ID_FIELD)
    today = data.get("today")
    spray_area = data.get(SPRAY_AREA_FIELD)
    if spray_area:
        # get location by spray_area
        try:
            spray_area = Location.objects.get(name=spray_area, level="ta")
        except Location.DoesNotExist:
            spray_area = None
        else:
            district = spray_area.parent.parent
            health_facility = spray_area.parent

    return Decision.objects.create(
        data=data,
        submission_id=submission_id,
        district=district,
        health_facility=health_facility,
        spray_area=spray_area,
        today=today,
    )

mspray/apps/main/models/district.py
# -*- coding: utf-8 -*-
"""
District model.
"""
from django.contrib.gis.db import models


class District(models.Model):
    """
    District model.
    """
    district_name = models.CharField(max_length=255, db_index=1)
    houses = models.IntegerField(db_index=1)
    geom = models.MultiPolygonField(srid=4326)
    code = models.CharField(max_length=10, db_index=1)

    class Meta:
        app_label = 'main'

    def __str__(self):
        return self.district_name

mspray/apps/main/models/household.py
# -*- coding: utf-8 -*-
"""
Household model.
"""
from django.contrib.gis.db import models
from django.contrib.postgres.fields import JSONField


class Household(models.Model):
    """
    Household model.
    """

    hh_id = models.IntegerField(unique=True)
    geom = models.PointField(srid=4326)
    bgeom = models.PolygonField(srid=4326, null=True, blank=True)
    location = models.ForeignKey(
        "Location", default=1, on_delete=models.CASCADE
    )
    rhc = models.ForeignKey(
        "Location",
        db_index=True,
        null=True,
        related_name="household_rhc_set",
        on_delete=models.CASCADE,
    )
    district = models.ForeignKey(
        "Location",
        db_index=True,
        null=True,
        related_name="houshold_district_set",
        on_delete=models.CASCADE,
    )
    data = JSONField(default=dict)
    visited = models.NullBooleanField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    sprayable = models.NullBooleanField(null=True)

    class Meta:
        app_label = "main"

    def __str__(self):
        return str(self.hh_id)

    @classmethod
    def by_osmid(cls, osmid):
        """Return a houshold object with the matching osmid for hh_id."""
        try:
            return cls.objects.get(hh_id=osmid)
        except cls.DoesNotExist:
            return None

    def _set_parent_locations(self):
        if self.location:
            if self.rhc != self.location.parent:  # pylint: disable=no-member
                self.rhc = self.location.parent  # pylint: disable=no-member
            if self.district != self.rhc.parent:  # pylint: disable=no-member
                self.district = self.rhc.parent  # pylint: disable=no-member

    # pylint: disable=arguments-differ
    def save(self, *args, **kwargs):
        self._set_parent_locations()

        return super(Household, self).save(*args, **kwargs)


# Auto-generated `LayerMapping` dictionary for Household model
household_mapping = {  # pylint: disable=C0103
    "hh_id": "OBJECTID",
    "geom": "POINT",
}

mspray/apps/main/models/households_buffer.py
# -*- coding: utf-8 -*-
"""
HouseholdsBuffer model.
"""
# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models


class HouseholdsBuffer(models.Model):
    """
    HouseholdsBuffer model
    """

    location = models.ForeignKey("Location", on_delete=models.CASCADE)
    num_households = models.IntegerField(default=0)
    geom = models.PolygonField(srid=4326)

    class Meta:
        app_label = "main"

mspray/apps/main/models/osm.py
from django.contrib.gis.db import models
from django.contrib.postgres.fields import JSONField


class Node(models.Model):
    node_id = models.BigIntegerField(unique=True)
    version = models.IntegerField()
    changeset = models.IntegerField()
    user = models.CharField(max_length=50, null=True)
    timestamp = models.DateTimeField(null=True)
    geom = models.PointField(srid=4326, null=True)
    tags = JSONField(default={}, null=True)

    class Meta:
        app_label = 'main'


class Way(models.Model):
    way_id = models.BigIntegerField(unique=True)
    action = models.CharField(max_length=20, null=True)
    version = models.IntegerField()
    changeset = models.IntegerField()
    user = models.CharField(max_length=50, null=True)
    timestamp = models.DateTimeField(null=True)
    geom = models.PolygonField(srid=4326, null=True)
    tags = JSONField(default={}, null=True)

    class Meta:
        app_label = 'main'

mspray/apps/main/models/team_leader.py
# -*- coding: utf-8 -*-
"""
TeamLeader model.
"""
from django.contrib.gis.db import models


class TeamLeader(models.Model):
    """
    TeamLeader model.
    """

    code = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=255, db_index=1)
    location = models.ForeignKey(
        "Location", null=True, on_delete=models.CASCADE
    )
    data_quality_check = models.BooleanField(default=False)
    average_spray_quality_score = models.FloatField(default=0.0)

    class Meta:
        app_label = "main"

    def __str__(self):
        return "{}".format(self.name)

mspray/apps/main/views/decision.py
# -*- coding: utf-8 -*-
"""
Decision view.
"""

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from mspray.apps.main.models.decision import create_decision_visit


class DecisionView(APIView):
    """Decision viewset."""

    def post(self, request):
        """Handle a Decision submission."""
        create_decision_visit(request.data)
        return Response(status=status.HTTP_201_CREATED)

mspray/apps/main/views/districts.py
from django.db.models import Count
from rest_framework import viewsets


from mspray.apps.main.models import TargetArea
from mspray.apps.main.serializers.district import DistrictSerializer
from mspray.apps.main.serializers.target_area import TargetAreaSerializer


class DistrictViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = TargetArea.objects.filter(targeted=TargetArea.TARGETED_VALUE)\
        .values('district_name')\
        .annotate(num_target_areas=Count('district_name'))
    serializer_class = DistrictSerializer

    def get_serializer_class(self):
        district = self.request.query_params.get('district')

        if district:
            return TargetAreaSerializer

        return super(DistrictViewSet, self).get_serializer_class()

    def filter_queryset(self, queryset):
        district = self.request.query_params.get('district')

        if district:
            queryset = TargetArea.objects.filter(
                targeted=TargetArea.TARGETED_VALUE,
                district_name=district
            ).order_by('targetid', 'houses')

        return queryset

mspray/apps/main/views/errors.py
# -*- coding: utf-8 -*
"""Custom 404 view."""
from django.shortcuts import render


def error_404(request, *args, **argv):
    """Render custom template."""
    data = {}
    template_name = '404.html'
    response = render(request, template_name, data)
    response.status_code = 404
    return response

mspray/apps/main/templates/spray-operator-daily.html
{% extends 'home/base.html' %}

{% load humanize %}
{% load staticfiles %}
{% load performance_extras %}

{% block content %}
        <div class="container">
            <h1>Data for: {{ spray_operator_name }}</h1>
            <ol class="breadcrumb">
              <li><a href="{% url "performance:districts" %}">Districts</a></li>
              <li><a href="{% url "performance:team-leaders" district.pk %}">{{SUPERVISOR_LABEL_PLURAL}}</a></li>
              <li><a href="{% url "performance:spray-operator-summary" district.pk team_leader %}">{{ COMMUNITY_HEALTH_WORKER_LABEL_PLURAL }}</a></li>
              <li class="active">{{ COMMUNITY_HEALTH_WORKER_LABEL }}</li>
            </ol>
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th rowspan="3">Day</th>
                                <th rowspan="3">Date</th>
                                <th colspan="5">Number of Structures</th>
                                <!-- <th rowspan="3">Spray Coverage</th> -->
                                <th rowspan="3">Data collection start time</th>
                                <th rowspan="3">Data collection end time</th>
                                <th rowspan="3">Duration in field</th>
                                <th rowspan="3">Data Quality Check</th>
                                <th rowspan="3">Found Difference</th>
                                <th rowspan="3">Sprayed Difference</th>
                            </tr>
                            <tr>
                                <th rowspan="2">Found</th>
                                <th rowspan="2">Sprayed</th>
                                <th colspan="3">Not sprayed</th>
                            </tr>
                            <tr>
                                <th>Refused</th>
                                <th>Other</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in data %}
                                <tr>
                                    <td>{{ forloop.counter }}</a></td>
                                    <td>{{ row.date|date:'d-M' }}</a></td>
                                    <td class='numbers'>{{ row.sprayable|intcomma  }}</td>
                                    <td class='numbers'>{{ row.sprayed|intcomma  }}</td>
                                    <td class='numbers'>{{ row.refused|intcomma  }}</td>
                                    <td class='numbers'>{{ row.other|intcomma  }}</td>
                                    <td class='numbers'>{{ row.not_sprayed_total }}</td>
                                    <!-- <td class='numbers'>{{ row.spray_success_rate }}%</td> -->
                                    <td class='numbers {{ row.avg_start_time|avg_start_time_color }}'>{{ row.avg_start_time|format_avg_time }}</td>
                                    <td class='numbers {{ row.avg_end_time|avg_end_time_color }}'>{{ row.avg_end_time|format_avg_time }}</td>
                                    <td class='numbers'>{% avg_time_interval row.avg_end_time row.avg_start_time %}</td>
                                    <td>
                                        {% if row.data_quality_check %}
                                            <i class="fa fa-check green" aria-hidden="true"></i>
                                        {% else %}
                                            <i class="fa fa-times red" aria-hidden="true"></i>
                                        {% endif %}
                                    </td>
                                    <td>{{ row.found_difference }}</td>
                                    <td>{{ row.sprayed_difference }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="2">Totals</td>
                                <td class='numbers'>{{ totals.sprayable|intcomma  }}</td>
                                <td class='numbers'>{{ totals.sprayed|intcomma  }}</td>
                                <td class='numbers'>{{ totals.refused|intcomma  }}</td>
                                <td class='numbers'>{{ totals.other|intcomma  }}</td>
                                <td class='numbers'>{{ totals.not_sprayed_total }}</td>
                                <!-- <td class='numbers'>{{ totals.spray_success_rate }}%</td> -->
                                <td class='numbers {{ totals.avg_start_time|avg_start_time_color }}'>{{ totals.avg_start_time|format_avg_time }}</td>
                                <td class='numbers {{ totals.avg_end_time|avg_end_time_color }}'>{{ totals.avg_end_time|format_avg_time }}</td>
                                <td class='numbers'>{% avg_time_interval totals.avg_end_time totals.avg_start_time %}</td>
                                <td>
                                    {% if totals.data_quality_check %}
                                        <i class="fa fa-check green" aria-hidden="true"></i>
                                    {% else %}
                                        <i class="fa fa-times red" aria-hidden="true"></i>
                                    {% endif %}
                                </td>
                                <td>{{ totals.found_difference }}</td>
                                <td>{{ totals.sprayed_difference }}</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        {% include 'definitions-and-conditions.html' %}
        </div>
{% endblock %}

mspray/apps/main/templates/spray-operator-summary.html
{% extends 'home/base.html' %}

{% load humanize %}
{% load staticfiles %}
{% load performance_extras %}

{% block content %}
        <div class="container">
            <h1>{{ team_leader_name }}</h1>
            <ol class="breadcrumb">
              <li><a href="{% url "performance:districts" %}">Districts</a></li>
              <li><a href="{% url "performance:team-leaders" district.pk %}">{{ SUPERVISOR_LABEL_PLURAL }}</a></li>
               <li class="active">{{ COMMUNITY_HEALTH_WORKER_LABEL_PLURAL }}</li>
            </ol>
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th rowspan="2">{{ COMMUNITY_HEALTH_WORKER_LABEL }}</th>
                                <th rowspan="2">Number of <br/> days worked</th>
                                <th colspan="3">Structures</th>
                                <!-- <th rowspan="2">Spray Coverage</th> -->
                                <th rowspan="2">Average structures <br />found per day</th>
                                <th rowspan="2">Average start time</th>
                                <th rowspan="2">Average end time</th>
                                <th rowspan="2">Duration in field</th>
                                <th rowspan="2">Data Quality Check</th>
                                <th rowspan="2">Found Difference (Latest Submission)</th>
                                <th rowspan="2">Sprayed Difference (Latest Submission)</th>
                            </tr>
                            <tr>
                                <th rowspan="2">Found</th>
                                <th rowspan="2">Sprayed</th>
                                <th rowspan="2">Not sprayed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in data %}
                                <tr>
                                    {% if not IS_MDA_LINK and not IS_MDA_2_LINK %}
                                    <td><a href="{% url PERFORMANCE_SO_URL district.id team_leader row.spray_operator_id %}">{{ row.name }}</a></td>
                                    {% else %}
                                    <td><a href="{% url PERFORMANCE_SO_URL district.id row.spray_operator_id %}">{{ row.name }}</a></td>
                                    {% endif %}
                                    <td class='numbers'>{{ row.no_of_days_worked|intcomma   }}</td>
                                    <td class='numbers'>{{ row.sprayable|intcomma  }}</td>
                                    <td class='numbers'>{{ row.sprayed|intcomma  }}</td>
                                    <td class='numbers'>{{ row.not_sprayed_total }}</td>
                                    <!-- <td class='numbers'>{{ row.spray_success_rate }}%</td> -->
                                    <td class='numbers {{ row.avg_structures_per_so|sprayed_color }}'>
                                        {{row.avg_structures_per_so|floatformat:"0" }}
                                    </td>
                                    <td class='numbers {{ row.avg_start_time|avg_start_time_color }}'>{{ row.avg_start_time|format_avg_time }}</td>
                                    <td class='numbers {{ row.avg_end_time|avg_end_time_color }}'>{{ row.avg_end_time|format_avg_time }}</td>
                                    <td class='numbers'>{% avg_time_interval row.avg_end_time row.avg_start_time %}</td>
                                    <td>
                                        {% if row.data_quality_check %}
                                            <i class="fa fa-check green" aria-hidden="true"></i>
                                        {% else %}
                                            <i class="fa fa-times red" aria-hidden="true"></i>
                                        {% endif %}
                                    </td>
                                    <td>{{ row.found_difference }}</td>
                                    <td>{{ row.sprayed_difference }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>Totals</td>
                                <td class='numbers'>{{ totals.no_of_days_worked|intcomma  }}</td>
                                <td class='numbers'>{{ totals.sprayable|intcomma  }}</td>
                                <td class='numbers'>{{ totals.sprayed|intcomma  }}</td>
                                <td class='numbers'>{{ totals.not_sprayed_total }}</td>
                                <!-- <td class='numbers'>{{ totals.spray_success_rate }}%</td> -->
                                <td class='numbers {{ totals.avg_structures_per_so|sprayed_color }}'>
                                    {{ totals.avg_structures_per_so|floatformat:"0" }}
                                </td>
                                <td class='numbers {{ totals.avg_start_time|avg_start_time_color }}'>{{ totals.avg_start_time|format_avg_time }}</td>
                                <td class='numbers {{ totals.avg_end_time|avg_end_time_color }}'>{{ totals.avg_end_time|format_avg_time }}</td>
                                <td class='numbers'>{% avg_time_interval totals.avg_end_time totals.avg_start_time %}</td>
                                <td>
                                    {% if totals.data_quality_check %}
                                        <i class="fa fa-check green" aria-hidden="true"></i>
                                    {% else %}
                                        <i class="fa fa-times red" aria-hidden="true"></i>
                                    {% endif %}
                                </td>
                                <td>{{ totals.found_difference }}</td>
                                <td>{{ totals.sprayed_difference }}</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        {% include 'definitions-and-conditions.html' %}
        </div>
{% endblock %}